version: '3'

services:
    backend:
        build: .
        restart: always
        volumes:
            - .:/app
        ports:
            - 8000:8000
        image: app:django
        container_name: django_container
        command: python manage.py runserver 0.0.0.0:8000
        environment:
          - DB_HOST=postgres-db
          - DB_USER=postgres
          - DB_PASSWORD=postgres
          - DJANGO_SUPERUSER_PASSWORD=admin
        depends_on:
            - postgres-db

    frontend:
        build:
            context: ./client
        restart: always
        volumes:
          - ./client:/app
          - /app/node_modules
        ports:
            - 3000:3000
        image: app:react
        container_name: react_container
        command: npm start

    postgres-db:
         image: postgres
         restart: always
         volumes:
           - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
         ports:
           - 5432:5432
         environment:
           - POSTGRES_DB=weather
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres
           - PGDATA=/var/lib/postgresql/data/some_name/

volumes:
  postgres_volume:





