# Generated by Django 4.1.1 on 2022-09-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('screen', models.ImageField(upload_to='screen/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
