# Generated by Django 4.1.1 on 2023-01-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyscreen',
            name='screen',
            field=models.ImageField(upload_to='%Y/%m/%d/'),
        ),
    ]
